Str = " Hella Python world! Let's learn Python. "
print(Str.upper())
print(Str.index("Python"))
print(Str.startswith("WELCOME"))
print(Str.isalpha())
print(Str.isdigit())
print(Str.split())
lst = Str.split()
print(", ".join(lst))
print(Str[0:6])
print(Str[::-1])
print(Str + " -END")
print(Str + Str )
print(Str.count("a"))
print(Str.strip())
